#!/bin/bash

#Indicate Start of Download
echo "Starting to Fetch Airfoil Data..."

# For Airfoil Eppler 420      
wget http://airfoiltools.com/airfoil/seligdatfile?airfoil=e420-il -O Eppler_420.dat

# For Airfoil Eppler E423     
wget http://airfoiltools.com/airfoil/seligdatfile?airfoil=e423-il -O Eppler_E_423.dat

# For Airfoil S1223           
wget http://airfoiltools.com/airfoil/seligdatfile?airfoil=s1223-il -O S1223.dat

# For Airfoil S1223 RTL       
wget http://airfoiltools.com/airfoil/seligdatfile?airfoil=s1223rtl-il -O S1223_RTL.dat

# For Airfoil Chuch Hollinger 
wget http://airfoiltools.com/airfoil/seligdatfile?airfoil=ch10sm-il -O Church_Hollinger.dat

# For Airfoil Curtiss CR-1    
wget http://airfoiltools.com/airfoil/seligdatfile?airfoil=cr1-il -O Curtiss_CR1.dat

# For Airfoil Drela DAE11     
wget http://airfoiltools.com/airfoil/seligdatfile?airfoil=dae11-il -O Drela_DAE11.dat

# For Airfoil Drela DAE21     
wget http://airfoiltools.com/airfoil/seligdatfile?airfoil=dae21-il -O Drela_DAE21.dat

# For Airfoil Drela DAE31     
wget http://airfoiltools.com/airfoil/seligdatfile?airfoil=dae31-il -O Drela_DAE31.dat

# For Airfoil Lissaman 7769   
wget http://airfoiltools.com/airfoil/seligdatfile?airfoil=l7769-il -O Lissaman_7769.dat

#Customary End
echo "Finished Fetching..."
